### ISSUE TITLE
ERROR TypeError: Cannot read properties of undefined (reading 'setCalendarTimezone')

### ISSUE THREAD

**Issue by R3zu3** [syncfusion/ej2-angular-ui-components#279]
Hello, I have a small bug when changing the calendar time zone  
Summarizing my implementation, I have the following:

**Component.html**

`<ejs-schedule [timezone]="timeZone"></ejs-schedule>`  
  
**Component.ts**  
  
`@ViewChild('calendar') calendar!: ScheduleComponent;`  
  
I tried all the combinations of this instructions and they all give an error.  
  
`setTimeZone(zone: string) {`  
 `this.timeZone = zone;`  
 `this.calendar.setProperties({ timeZone: zone });`  
 `this.calendar.render();`  
`}`  
  
The MX and VE buttons are to test the time zone change

![](https://github.com/user-attachments/assets/6103ff26-7031-4f5b-a42b-f7806786dbe4)

When I change the zone, the events are updated correctly at the corresponding time and vice versa, but the error breaks the calendar and I have to restart to enable it, render() refreshes it but it remains broken in the same way

![](https://github.com/user-attachments/assets/fe62fa3c-6d1f-45e3-b239-e9ee524dd105)

  
Anyway the error seems widespread and breaks the calendar instance (apparently)

  
Reviewing the error trace it seems that the schedule.js file on line 1548 is missing the same validation that is on lines 1443, 1458, 1527  
  
 schedule.js

![](https://github.com/user-attachments/assets/a13c40d4-651f-4c8a-bdfa-4d7022b4ad32)

 schedule.js

![](https://github.com/user-attachments/assets/0ddb3174-c92e-441f-99ad-2c49f910e94d)

calendar-home.component.html:127 ERROR TypeError: Cannot read properties of undefined (reading 'setCalendarTimezone')  
   at Schedule2.onPropertyChanged (schedule.js:1548:39)  
   at Base2.dataBind (base.js:120:18)  
   at Component2.dataBind (component.js:285:35)  
   at timer (zone.js:2367:41)  
   at \_ZoneDelegate.invokeTask (zone.js:402:31)  
   at core.mjs:14556:55  
   at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:14556:36)  
   at \_ZoneDelegate.invokeTask (zone.js:401:60)  
   at Object.onInvokeTask (core.mjs:14869:33)  
   at \_ZoneDelegate.invokeTask (zone.js:401:60)

Thanks regards, I hope I'm not wrong. ;)

**Comment by SwathiRavi14** [comment]
@R3zu3,

To address the time zone change issue, you can simply update the timeScale property without needing to re-render the entire component. We have attached a sample for your reference that demonstrates how to change the time zone effectively.

 

Demo: [https://ej2.syncfusion.com/angular/demos/#/tailwind3/schedule/timezone-event](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fej2.syncfusion.com%2Fangular%2Fdemos%2F%23%2Ftailwind3%2Fschedule%2Ftimezone-event&data=05%7C02%7Cswathi.ravi%40syncfusion.com%7C1fad4360ef8a413405e808dd4c30cf70%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638750494698985859%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=dhI1lP6epJxrCnKQnEiL3Z5cCOaGcqsTtjOVnVZLLH0%3D&reserved=0)
